# Main Configuration for Jenova AI - JCA v1.0
# Optimized for AMD Ryzen 7 5700U with Radeon Graphics
hardware:
  threads: 16
  gpu_layers: 35 # A good starting point for integrated AMD graphics
  mlock: true
model:
  embedding_model: 'all-MiniLM-L6-v2'
  context_size: 4096 # Will be dynamically overridden by model's max capacity if smaller
  temperature: 0.4
  top_p: 0.9
memory:
  episodic_db_path: "memory_db/episodic"
  semantic_db_path: "memory_db/semantic"
  procedural_db_path: "memory_db/procedural"
  reflection_interval: 3 # Reflect every 3 conversation turns

finetuning:
  training_file: "finetune_train.jsonl"
  lora_output_file: "models/lora-jenova-adapter.bin"